// <auto-generated />
using System;
using DockingApiService.DataModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DockingApiService.Migrations
{
    [DbContext(typeof(ComputationContext))]
    [Migration("20181107175312_AddBbbScoresAndDepictionSvg")]
    partial class AddBbbScoresAndDepictionSvg
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("GpcrPredictionOnline.DataModels.DockingLigand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float?>("BbbAdaboostDayLight");

                    b.Property<float?>("BbbAdaboostMACCS");

                    b.Property<float?>("BbbAdaboostMolprint2D");

                    b.Property<float?>("BbbAdaboostPubChem");

                    b.Property<float?>("BbbSVMDayLight");

                    b.Property<float?>("BbbSVMMACCS");

                    b.Property<float?>("BbbSVMMolprint2D");

                    b.Property<float?>("BbbSVMPubChem");

                    b.Property<string>("DepictionSvg");

                    b.Property<string>("DepictionSvg3D");

                    b.Property<byte[]>("Fingerprint");

                    b.Property<int>("Progress");

                    b.Property<string>("Smiles");

                    b.HasKey("Id");

                    b.ToTable("DockingLigands");
                });

            modelBuilder.Entity("GpcrPredictionOnline.DataModels.DockingResult", b =>
                {
                    b.Property<long>("LigandId");

                    b.Property<int>("ProteinId");

                    b.Property<float?>("ConfidenceLevel");

                    b.Property<DateTimeOffset>("Created");

                    b.Property<int?>("Prediction");

                    b.Property<float?>("Score1");

                    b.Property<float?>("Score2");

                    b.Property<float?>("Score3");

                    b.Property<float?>("Score4");

                    b.Property<int?>("SimilarChemblId");

                    b.Property<byte[]>("SimilarFingerprint");

                    b.Property<string>("SimilarSmiles");

                    b.Property<DateTimeOffset>("Updated");

                    b.HasKey("LigandId", "ProteinId");

                    b.ToTable("DockingResults");
                });

            modelBuilder.Entity("GpcrPredictionOnline.DataModels.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("Created");

                    b.Property<long>("LigandId");

                    b.Property<string>("Name");

                    b.Property<DateTimeOffset>("Started");

                    b.Property<int>("Status");

                    b.Property<DateTimeOffset>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("LigandId");

                    b.ToTable("DockingTasks");
                });

            modelBuilder.Entity("GpcrPredictionOnline.DataModels.DockingResult", b =>
                {
                    b.HasOne("GpcrPredictionOnline.DataModels.DockingLigand", "Ligand")
                        .WithMany("Results")
                        .HasForeignKey("LigandId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GpcrPredictionOnline.DataModels.Job", b =>
                {
                    b.HasOne("GpcrPredictionOnline.DataModels.DockingLigand", "Ligand")
                        .WithMany("Jobs")
                        .HasForeignKey("LigandId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
