// <auto-generated />
using DockingApiService.DataModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DockingApiService.Migrations
{
    [DbContext(typeof(ComputationContext))]
    [Migration("20180301170246_InitCreate")]
    partial class InitCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("GpcrPredictionOnline.DataModels.DockingLigand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Fingerprint");

                    b.Property<int>("Progress");

                    b.Property<string>("Smiles");

                    b.HasKey("Id");

                    b.ToTable("DockingLigands");
                });

            modelBuilder.Entity("GpcrPredictionOnline.DataModels.DockingResult", b =>
                {
                    b.Property<long>("LigandId");

                    b.Property<int>("ProteinId");

                    b.Property<DateTimeOffset>("Created");

                    b.Property<int?>("Prediction");

                    b.Property<float?>("Score1");

                    b.Property<float?>("Score2");

                    b.Property<float?>("Score3");

                    b.Property<float?>("Score4");

                    b.Property<int?>("SimilarChemblId");

                    b.Property<byte[]>("SimilarFingerprint");

                    b.Property<string>("SimilarSmiles");

                    b.Property<DateTimeOffset>("Updated");

                    b.HasKey("LigandId", "ProteinId");

                    b.ToTable("DockingResults");
                });

            modelBuilder.Entity("GpcrPredictionOnline.DataModels.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("Created");

                    b.Property<long>("LigandId");

                    b.Property<string>("Name");

                    b.Property<DateTimeOffset>("Started");

                    b.Property<int>("Status");

                    b.Property<DateTimeOffset>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("LigandId");

                    b.ToTable("DockingTasks");
                });

            modelBuilder.Entity("GpcrPredictionOnline.DataModels.DockingResult", b =>
                {
                    b.HasOne("GpcrPredictionOnline.DataModels.DockingLigand", "Ligand")
                        .WithMany("Results")
                        .HasForeignKey("LigandId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GpcrPredictionOnline.DataModels.Job", b =>
                {
                    b.HasOne("GpcrPredictionOnline.DataModels.DockingLigand", "Ligand")
                        .WithMany("Jobs")
                        .HasForeignKey("LigandId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
